### ISSUE TITLE
CF_VALUE_JSON is not defined

### ISSUE THREAD

**Issue by ilkosta** [taikii/redmine_custom_auto_complete#1]
Hi, 
from Firefox and from Chromium I got these errors:
```
ReferenceError: CF_VALUE_JSON is not defined[Learn More] issue_dynamic_edit.js:130:18
initEditFields
https://pass.regione.marche.it/plugin_assets/redmine_issue_dynamic_edit/javascripts/issue_dynamic_edit.js:130:18
<anonymous>
https://pass.regione.marche.it/plugin_assets/redmine_issue_dynamic_edit/javascripts/issue_dynamic_edit.js:172:1
```

in Chromium seems to work, in Firefox no.

**Comment by taikii** [comment]
It seems to me a problem of [Issue dynamic edit plugin](https://github.com/Ilogeek/redmine_issue_dynamic_edit).
Perhaps it may be in conflict with my plugin, but I'm not sure.

**Comment by ilkosta** [comment]
after removing `Issue dynamic edit plugin` it works perfectly.
