### ISSUE TITLE
flag `Custom fields auto complete` in project modules

### ISSUE THREAD

**Issue by ilkosta** [taikii/redmine_custom_auto_complete#2]
If I enable the flag `Custom fields auto complete` from the project modules, when a I create a new ticket, custom fields no longer appear.

**Comment by taikii** [comment]
@ilkosta
Is the cause of this issue different from #1?
Please let me know the error message if you have.

**Comment by ilkosta** [comment]
All problem solved removing `Issue dynamic edit plugin`.
Thanks
