### ISSUE TITLE
Data for field

### ISSUE THREAD

**Issue by Hypser** [taikii/redmine_custom_auto_complete#4]
I have installed the plugin now and i got the little mag. glass on the text field. But where do i put the data the field should search in? 
I was hoping to use it for a custom customer lister, and be able to easy search in the list.

**Comment by taikii** [comment]
This plugin assists you by listing the history of past entries in the same custom field. So, no master data is required.

**Comment by Hypser** [comment]
Okay now i understand. 
Then i cant use it :)
I need it to hold some master data, then it would be perfect. 

Thansk for the quick reply and have a great day.
